CREATE DATABASE hib4
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Polish_Poland.1250'
    LC_CTYPE = 'Polish_Poland.1250'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

CREATE TABLE public.author
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    username character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT author_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE public.author
    OWNER to postgres;

CREATE TABLE public.author_roles
(
    authors_id integer NOT NULL,
    roles_id integer NOT NULL,
    CONSTRAINT fkahc652wg5cdrfaftwidmk56w7 FOREIGN KEY (authors_id)
        REFERENCES public.author (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkcw7sekslqfyheebpps2fo96cp FOREIGN KEY (roles_id)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE public.author_roles
    OWNER to postgres;

CREATE TABLE public.post
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    content character varying(255) COLLATE pg_catalog."default",
    author_id integer,
    CONSTRAINT post_pkey PRIMARY KEY (id),
    CONSTRAINT fk5l759v7apba3lqguc7bp8h456 FOREIGN KEY (author_id)
        REFERENCES public.author (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE public.post
    OWNER to postgres;

CREATE TABLE public.roles
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    role character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE public.roles
    OWNER to postgres;

INSERT INTO public.roles(
    id, role)
VALUES (1, 'Admin');

INSERT INTO public.roles(
    id, role)
VALUES (2, 'User');

INSERT INTO public.roles(
    id, role)
VALUES (3, 'Guest');

INSERT INTO public.roles(
    id, role)
VALUES (4, 'Unknown');